# Generated by Django 4.0.5 on 2022-06-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='bdaydate',
        ),
    ]
